[package]
name = "bin"
version = "0.1.0"
edition = "2021"
authors = ["happyboy"]

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4.1", features = ["derive"] }
humbird = { path = "../humbird" }
tracing = "0.1.37"
tracing-subscriber = "0.3"
tracing-appender = "0.2.2"
chrono = "0.4.30"