[package]
name = "humbird"
version = "0.1.0"
edition = "2021"
authors = ["happyboy"]

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.7.6"
tracing = "0.1.37"
serde = { version = "1.0", features = ["derive"] }
regex = "1.9.4"
